### ISSUE TITLE
Please complete README.md

### ISSUE THREAD

**Issue by Msegun** [mbarzowska/generating-music-for-dummies#1]
I'm a dummy and i want to generate music. Without proper instruction I am lost. Please complete README.md

**Comment by mbarzowska** [comment]
Have you tried not being a dummy? I'm sure it helps a lot.

**Comment by illumitata** [comment]
XDDD


czw., 13 sie 2020 o 12:14 Msegun <notifications@github.com> napisał(a):

**Comment by Msegun** [comment]
Sadly beeing a dum dum is not a choice :(
